language: ruby

sudo: false

rvm:
  - 2.1.5

env:
  - DB=postgresql

before_script:
  - psql -c 'create database wodup_test;' -U postgres

script:
  - ./script/cibuild

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

notifications:
  email: false
