default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/moviebase_development

test:
  <<: *default
  database: db/moviebase_test

production:
  <<: *default
  database: db/moviebase
