default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/wodup_development

test:
  <<: *default
  database: db/wodup_test

production:
  <<: *default
  database: db/wodup
